GET http://localhost:3003/products
content-type: application/json


###
POST http://localhost:3003/orders
content-type: application/json

{
    "name_client": "Samyr Hissa",
    "delivery_date": "01/12/2021"
    
}

###
GET http://localhost:3003/orders
content-type: application/json


###

GET http://localhost:3003/orders/58a8bd3c-a236-4de4-a49a-b58cbfc30892
content-type: application/json


###
GET http://localhost:3003/orders/itens/58a8bd3c-a236-4de4-a49a-b58cbfc30892
content-type: application/json



###
POST http://localhost:3003/orders/itens
content-type: application/json

{
    "order_id": "58a8bd3c-a236-4de4-a49a-b58cbfc30892",
    "product_id": "25",
    "qty_requested": 15
}

###
PUT http://localhost:3003/orders/itens
content-type: application/json

{
    "item_id": "031eb064-a284-43e6-a49e-ae317fe743d9",
    "qty_alter": 5
}

###
DELETE http://localhost:3003/orders/itens/34cd210b-5d57-41b9-94e3-4dfaaee64c22
content-type: application/json



