GET http://localhost:3003/products
content-type: application/json


###
POST http://localhost:3003/orders
content-type: application/json

{
    "name_client": "Samyr Hissa",
    "delivery_date": "01/12/2021"
    
}

###
GET http://localhost:3003/orders
content-type: application/json


###

GET http://localhost:3003/orders/b3b4a44b-e34c-41fc-a99a-4a7d977b99d
content-type: application/json


###
GET http://localhost:3003/orders/itens/b3b4a44b-e34c-41fc-a99a-4a7d977b99d3
content-type: application/json



###
POST http://localhost:3003/orders/itens
content-type: application/json

{
    "order_id": "b3b4a44b-e34c-41fc-a99a-4a7d977b99d3",
    "product_id": "23",
    "qty_requested": 25
}

###
PUT http://localhost:3003/orders/itens
content-type: application/json

{
    "item_id": "694a6370-3b5b-4c96-a7a3-5fa83f3d8668",
    "qty_alter": 5
}

###
DELETE http://localhost:3003/orders/itens/694a6370-3b5b-4c96-a7a3-5fa83f3d8668
content-type: application/json



